package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1


import java.util.Set;

/**
 * Auth generated by hbm2java
 */
public class Auth  implements java.io.Serializable {


     private Integer id;
     private String password;

    public Auth() {
    }

    public Auth(String password, Set users) {
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
}


