package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1



/**
 * Linecart generated by hbm2java
 */
public class Linecart  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Shoppingcart shoppingcart;
     private Integer quantity;
     private Integer price;

    public Linecart() {
    }

	
    public Linecart(Item item, Shoppingcart shoppingcart) {
        this.item = item;
        this.shoppingcart = shoppingcart;
    }
    public Linecart(Item item, Shoppingcart shoppingcart, Integer quantity, Integer price) {
       this.item = item;
       this.shoppingcart = shoppingcart;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Shoppingcart getShoppingcart() {
        return this.shoppingcart;
    }
    
    public void setShoppingcart(Shoppingcart shoppingcart) {
        this.shoppingcart = shoppingcart;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


