package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shippinginfo generated by hbm2java
 */
public class Shippinginfo  implements java.io.Serializable {


     private Integer id;
     private Integer shippingPrice;
     private String carrier;
     private Set orderses = new HashSet(0);

    public Shippinginfo() {
    }

    public Shippinginfo(Integer shippingPrice, String carrier, Set orderses) {
       this.shippingPrice = shippingPrice;
       this.carrier = carrier;
       this.orderses = orderses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getShippingPrice() {
        return this.shippingPrice;
    }
    
    public void setShippingPrice(Integer shippingPrice) {
        this.shippingPrice = shippingPrice;
    }
    public String getCarrier() {
        return this.carrier;
    }
    
    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


