package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shoppingcart generated by hbm2java
 */
public class Shoppingcart  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Set linecarts = new HashSet(0);

    public Shoppingcart() {
    }

	
    public Shoppingcart(User user) {
        this.user = user;
    }
    public Shoppingcart(User user, Set linecarts) {
       this.user = user;
       this.linecarts = linecarts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getLinecarts() {
        return this.linecarts;
    }
    
    public void setLinecarts(Set linecarts) {
        this.linecarts = linecarts;
    }




}


