package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stockorder generated by hbm2java
 */
public class Stockorder  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String date;
     private Set linestocks = new HashSet(0);

    public Stockorder() {
    }

	
    public Stockorder(User user) {
        this.user = user;
    }
    public Stockorder(User user, String date, Set linestocks) {
       this.user = user;
       this.date = date;
       this.linestocks = linestocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Set getLinestocks() {
        return this.linestocks;
    }
    
    public void setLinestocks(Set linestocks) {
        this.linestocks = linestocks;
    }




}


