package com.figureitout.model.entities;
// Generated 1 mars 2018 16:29:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Auth auth;
     private String name;
     private String firstName;
     private String mail;
     private String signupDate;
     private Boolean deleted;
     private String role;
     private Set sessions = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set transactions = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set shoppingcarts = new HashSet(0);
     private Set stockorders = new HashSet(0);
     private Set addresses = new HashSet(0);

    public User() {
    }

	
    public User(String role) {
        this.role = role;
    }
    public User(Auth auth, String name, String firstName, String mail, String signupDate, Boolean deleted, String role, Set sessions, Set comments, Set transactions, Set orderses, Set ratings, Set shoppingcarts, Set stockorders, Set addresses) {
       this.auth = auth;
       this.name = name;
       this.firstName = firstName;
       this.mail = mail;
       this.signupDate = signupDate;
       this.deleted = deleted;
       this.role = role;
       this.sessions = sessions;
       this.comments = comments;
       this.transactions = transactions;
       this.orderses = orderses;
       this.ratings = ratings;
       this.shoppingcarts = shoppingcarts;
       this.stockorders = stockorders;
       this.addresses = addresses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Auth getAuth() {
        return this.auth;
    }
    
    public void setAuth(Auth auth) {
        this.auth = auth;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getSignupDate() {
        return this.signupDate;
    }
    
    public void setSignupDate(String signupDate) {
        this.signupDate = signupDate;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Set sessions) {
        this.sessions = sessions;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getShoppingcarts() {
        return this.shoppingcarts;
    }
    
    public void setShoppingcarts(Set shoppingcarts) {
        this.shoppingcarts = shoppingcarts;
    }
    public Set getStockorders() {
        return this.stockorders;
    }
    
    public void setStockorders(Set stockorders) {
        this.stockorders = stockorders;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


